scheduler: main.cpp
	g++ -o scheduler main.cpp -std=c++11 -Wall -Werror -Wextra -O3

inputGenerator: inputGenerator.x.cpp
	g++ -o inputGenerator inputGenerator.x.cpp -Wall -Werror -Wextra -O3

clean:
	$(RM) scheduler inputGenerator
