feedHandler: main.cpp
	clang -o feedhandler main.cpp FeedHandler.cpp Book.cpp -std=c++0x -O3 -Wall

debug: main.cpp
	clang -o feedhandler main.cpp FeedHandler.cpp Book.cpp -std=c++0x -g

clean:
	$(RM) feedhandler
