rpsGame: main.cpp
	g++ -o book main.cpp Book.cpp -std=c++0x -Wall -O3

LIBS = -lboost_unit_test_framework

#test:	PostFixCalculator.cpp PostFixCalculator.t.cpp
#	g++ -o test PostFixCalculator.cpp PostFixCalculator.t.cpp $(LIBS)

clean:
	$(RM) book
